### ISSUE TITLE
Font will not work even after running build script

### ISSUE THREAD

**Issue by ClassicAJ** [aliftype/rana-kufi#14]
Step 1: Download the source code
Step 2: Extract ZIP
Step 3: Find the build.py in "Scripts" and run it
Step 4: Open the font file

Unfortunately, I cannot seem to get this font to open even after running the build script. This doesn't exactly surprise me considering that this is still "Under Construction", but the fact this won't even open is a problem that completely prevents further testing of the font. I strongly advise this issue be fixed. Maybe it's just me, and someone here can help?

**Comment by khaledhosny** [comment]
You can download the font file from https://github.com/aliftype/rana-kufi/tree/main/fonts, you don’t need to build it. But you need to provide more details on how you are opening the file and how it does not work.
